const groups = [
  { title: "The right fit", items: [["What kinds of projects are a fit?", "We are most useful when a business needs a website that earns trust, an e-commerce experience, a clearer brand system, or custom software to replace a process that is holding the team back."], ["Do you only work with African businesses?", "No. We are rooted in Accra and Abuja, work closely with businesses across Africa, and partner with ambitious teams wherever the work makes sense."]] },
  { title: "Scope & shape", items: [["What do you actually build?", "Websites, e-commerce experiences, brand systems, and custom software — including internal tools, business applications and integrations."], ["Can you work with an existing team?", "Yes. We can lead a focused delivery or work alongside an in-house team, founders, and existing technical partners."]] },
  { title: "Process & timing", items: [["How do engagements begin?", "Tell us what is not working, what you need to achieve and when you need it. We will ask the practical questions, review what you have and tell you whether we can help. If we are a fit, you receive a clear scope, cost and delivery plan before work starts."], ["How long does a project take?", "It depends on what needs to be built, how ready the content and decisions are, and who needs to be involved on your side. Before work starts, we agree the scope, milestones and delivery plan—so you know what is happening and when."]] },
  { title: "Working together", items: [["How do you price work?", "Against the scope, agreed before we start. You will know what the project costs and what it includes before any of it is built — no hourly clock, no moving target."], ["Why begin on WhatsApp?", "It is a direct route to the people doing the work. Share the context in the way that is easiest for you, and we will respond personally."]] },
];

export default function StudioFaq() {
  return <section className="studio-faq"><div className="studio-label"><span>05</span><span>COMMON QUESTIONS</span></div><div className="studio-faq__grid">{groups.map((group) => <section key={group.title}><h2>{group.title}</h2><div>{group.items.map(([question, answer]) => <article key={question}><h3>{question}</h3><p>{answer}</p></article>)}</div></section>)}</div></section>;
}
